### ISSUE TITLE
Channel icons missing in iOS app

### ISSUE THREAD

**Issue by rusty1281** [RocketChat/Rocket.Chat.iOS#2393]
- Your Rocket.Chat app version: 3.1.2 (218)
- Your Rocket.Chat server version: 0.71.1
- Device (or Simulator) you're running with: iPhone 6 (latest iOS version)

Before I continue I have to say that I love the app and we are using 2 separate chat servers with this platform. Also no problem on the web and desktop end, just a small problem on the mobile side.

Now I am reporting this primarly as a ios problem, but users of Android OS are also reporing the same.

The problem is that the channel icons are not visible (the letters), just a small place holder on the bottom of the icon. Uploaded user avatars are visible just fine.

Is this a client side or server side problem? Again the web and desktop app display the letters and avatars just fine.

Thank you in advance for any info on the matter.

**Comment by rusty1281** [comment]
Hello @rafaelks. Here it is 
https://imgur.com/a/dz5NxG5

**Comment by geekgonecrazy** [comment]
What deployment method are you using?  Happen to have deployed snap on raspberry pi?

**Comment by rusty1281** [comment]
Docker official image

**Comment by rusty1281** [comment]
Hi there... any info on the matter?

tnx

**Comment by rusty1281** [comment]
Hi there. New update from today still didn’t fix this problem... just bumping a bit. 

thx!

**Comment by litewhatever** [comment]
Seeing same issue, deployed via Docker official image.

**Comment by rusty1281** [comment]
Just bummping this matter a bit? Is there any chance that this might get fixed in an upcoming version 0.73? Or is this an iOS problem?

**Comment by rafaelks** [comment]
@rusty1281 This is not an iOS client problem; this is a back-end problem... let me move this issue to our core repository.

**Comment by rafaelks** [comment]
@rusty1281 Is your server missing some font?

**Comment by anthonylavado** [comment]
Is this fixed by #2620? We have the same issue on our sever.

**Comment by rafaelks** [comment]
@anthonylavado @rusty1281 Have you guys tried using iOS 3.4 on the App Store today?

**Comment by rusty1281** [comment]
Icons are visible but they were also visible before today’s update. Guessing with latest server side update.

**Comment by rusty1281** [comment]
Still seeing filter and search problem tho https://github.com/RocketChat/Rocket.Chat.iOS/issues/2403#event-2077725533

**Comment by Shyru** [comment]
We also have this issue, and have deployed via the docker official image. (We are currently on Version 1.2.1) and both Rocket.Chat and Rocket.Chat Experimental with the newest versions show this issue.
This is really bugging us and keeping us from deploying rocket.chat company-wide for all users.
@rusty1281 If this is a server issue, how can this be fixed?

**Comment by rusty1281** [comment]
@Shyru - have to say that this was at one point fixed for me. Not sure was it the iOS side update or server side (pretty sure its server side) fix, but atm (for the past 2-3 version we have no problems.

**Comment by Shyru** [comment]
Ok, what a pitty. Can anybody help us on this issue?
Just for reference this is how it looks on our end:
![image](https://user-images.githubusercontent.com/957556/60808179-eec42680-a187-11e9-93fe-ff515f6e5111.png)
As you see, only custom sent avatar images are displayed. All channel-icons with only text only show a background color and some small character.
Is there anything more that we can do to help diagnose this error?

**Comment by umputun** [comment]
For me, the ios app is not even showing all custom (users) avatars, just some of them

**Comment by anthonylavado** [comment]
I should add, I still have this. I can see user avatars for Direct Messages, but not channel icons.

**Comment by j-stahl** [comment]
We finally solved this issue. @rafaelks was right. The font was missed. The website has shown the correct avatars, because they are drawn with CANVAS, while the mobile app gets a generated jpeg picture from backend.
The package fontconfig is not installed inside the docker image. So there are no fonts, the server app could use. I created a pull request to solve this issue in the next docker image builds. I created a pull request to solve that issue.
https://github.com/RocketChat/Docker.Official.Image/pull/92
To fix this now you can run:
`docker exec -it docker-container-name /bin/bash`
`apt-get update`
`apt-get install fontconfig`

@umputun Did you use also the docker image? Do you use filesystem to save your pictures?
Maybe you have forgot to use a docker mount to save the pictures on your host or on a docker volume. This will lead to missed pictures, when you destroy your container for updates.

**Comment by umputun** [comment]
> Did you use also the docker image?

yes

> Maybe you have forgot to use a docker mount 

No, the volume is mounted fine. Sometimes the issue can be "solved" by ios app reinstall.

**Comment by sampaiodiego** [comment]
Depends on https://github.com/docker-library/official-images/pull/7099

the release 2.3.1 of the official Docker image will fix the issue.. using our own maintained image does not have the issue: `rocketchat/rocket.chat:2.3.1`
